name: gh-pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p pages
      - run: cd tex && make all && cd ..
      - run: mv tex/*.pdf pages

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
        if: github.ref == 'refs/heads/main'
