name: gh-pages

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: mkdir -p public &&
             cd tex && make all && cd .. &&
             mv tex/*.pdf public &&
             ls public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        if: github.ref == 'refs/heads/main'
